apps:
  - script: ./bin/www
    name: 'Load Balancer'
    instances: 1
    watch: true
    exec_mode: cluster
  - script: ./scheduler.js
    name: 'Muba Crawler'
    instances: 0
    watch: true
    exec_mode: cluster